### ISSUE TITLE
Multiple effects with the same image but differing names do not have all effect names shown

### ISSUE THREAD

**Issue by witchydiana** [dor-fvtt-released-modules/combat-tracker-effect-tooltips#1]
Multiple effects with the same image but differing names do not have all effect names shown
As shown, the tooltip in the tracker has only one of the given effects applied to the character. Is there a way to show the names of both effects?
![image](https://user-images.githubusercontent.com/30417673/216469841-14ed204e-43a1-48db-9532-12bfc49ad5f3.png)
![image](https://user-images.githubusercontent.com/30417673/216469928-a694f1bb-e62e-4816-870f-b19e649baba7.png)

**Comment by Doresain** [comment]
Will look into this when updating for foundry v11.

**Comment by Doresain** [comment]
This will be solved in 3.1.0 for v10 and 11.0.0 for v11. 

Also, added a setting to duplicate the item instead.

Thanks for the report, @witchydiana !

**Comment by Doresain** [comment]
Closed.
